# Generated by Django 4.0.3 on 2022-03-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=11, verbose_name='date')),
                ('sick', models.IntegerField(verbose_name='sick')),
                ('sick_change', models.IntegerField(verbose_name='sick_change')),
                ('healed', models.IntegerField(verbose_name='healed')),
                ('healed_change', models.IntegerField(verbose_name='healed_change')),
            ],
        ),
    ]
